services:
  - type: web
    name: localsign
    env: node
    repo: https://github.com/cTatu/LocalSign
    branch: main
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /healthz
