// scripts/build-roots.mjs — regenerate js/roots.js from a Mozilla-style PEM bundle.
// Usage: node scripts/build-roots.mjs /path/to/cacert.pem
// The bundle is trust data (public root certificates), not secrets.
import fs from 'node:fs';

const src = process.argv[2] || '/tmp/roots/cacert.pem';
const pem = fs.readFileSync(src, 'utf8');
const blocks = pem.match(/-----BEGIN CERTIFICATE-----[^-]+-----END CERTIFICATE-----/g) || [];
const ders = blocks.map((b) => {
  const b64 = b.replace(/-----[^-]+-----/g, '').replace(/\s+/g, '');
  return Buffer.from(b64, 'base64').toString('base64');
});
const out = `// js/roots.js — GENERATED by scripts/build-roots.mjs. Do not hand-edit.
// Mozilla root store snapshot (${ders.length} self-signed trust anchors, PEM bundle
// dated by source file). Refresh yearly: node scripts/build-roots.mjs <cacert.pem>.
export const TRUST_ROOT_COUNT = ${ders.length};
export const TRUST_ROOTS = [
${ders.map((d) => `  '${d}',`).join('\n')}
];
`;
fs.writeFileSync(new URL('../js/roots.js', import.meta.url), out);
console.log(`wrote js/roots.js with ${ders.length} roots`);
